version: "3.8"

services:

    telegram_bot:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: tg_crypto_bot
        env_file:
            - .env
        image: worker
        command: python3 tgbot.py
        depends_on:
            - postgres
            - scheduler
        cap_add:
            - SYS_ADMIN

    create_tables:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: tg_crypto_bot_create_tables
        env_file:
            - .env
        image: worker
        command: python3 connectdb.py
        depends_on:
            - postgres
        cap_add:
            - SYS_ADMIN

    scheduler:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: tg_crypto_bot_scheduler
        env_file:
            - .env
        image: worker
        command: python3 models.py
        depends_on:
            - postgres
        cap_add:
            - SYS_ADMIN

    postgres:
        image: postgres
        container_name: tg-crypto-bot-postgres
        environment:
            - POSTGRES_USER=tgbotuser
            - POSTGRES_PASSWORD=mBFSH9lPvQj744OZ
            - POSTGRES_DB=tg_bot
        ports:
            - "5481:5432"
